# Data Structure Comparison: Tuple, List, NumPy ndarray, and Pandas DataFrame

## Table of Contents

1. [Introduction](#introduction)
2. [Tuple](#tuple)
3. [List](#list)
4. [NumPy ndarray](#numpy-ndarray)
5. [Pandas DataFrame](#pandas-dataframe)
6. [Comparison Summary](#comparison-summary)
7. [Conclusion](#conclusion)

## 1. Introduction <a id='introduction'></a>

This notebook provides a comprehensive comparison of four fundamental data structures in Python:
- **Tuple**: Immutable, ordered collection
- **List**: Mutable, ordered collection
- **NumPy ndarray**: Efficient multidimensional array
- **Pandas DataFrame**: Tabular data structure with labeled axes

## 2. Tuple <a id='tuple'></a>

### Definition and Basic Features
- **Definition**: A tuple is an immutable, ordered collection of elements.
- **Immutability**: Once created, elements cannot be added, removed, or modified.
- **Heterogeneous**: Can contain elements of different data types.
- **Ordered**: Elements maintain their insertion order.

In [1]:
# Tuple creation examples
# Method 1: Using parentheses
tuple1 = (1, 2, 3, 4, 5)
print('Tuple 1:', tuple1)

# Method 2: Without parentheses (tuple packing)
tuple2 = 1, 2, 3, 4, 5
print('Tuple 2:', tuple2)

# Method 3: Using tuple() constructor
tuple3 = tuple([1, 2, 3, 4, 5])
print('Tuple 3:', tuple3)

# Empty tuple
empty_tuple = ()
print('Empty tuple:', empty_tuple)

# Single-element tuple (must include comma)
single_element_tuple = (42,)
print('Single-element tuple:', single_element_tuple)

Tuple 1: (1, 2, 3, 4, 5)
Tuple 2: (1, 2, 3, 4, 5)
Tuple 3: (1, 2, 3, 4, 5)
Empty tuple: ()
Single-element tuple: (42,)


### Common Operations

In [2]:
# Accessing elements (indexing)
my_tuple = (10, 20, 30, 40, 50)
print('First element:', my_tuple[0])
print('Last element:', my_tuple[-1])

# Slicing
print('Slice from index 1 to 3:', my_tuple[1:4])
print('Every other element:', my_tuple[::2])

# Length
print('Length of tuple:', len(my_tuple))

# Concatenation
tuple_a = (1, 2, 3)
tuple_b = (4, 5, 6)
print('Concatenated tuple:', tuple_a + tuple_b)

# Repetition
print('Repeated tuple:', tuple_a * 3)

# Membership check
print('Is 20 in the tuple?', 20 in my_tuple)
print('Is 100 in the tuple?', 100 in my_tuple)

First element: 10
Last element: 50
Slice from index 1 to 3: (20, 30, 40)
Every other element: (10, 30, 50)
Length of tuple: 5
Concatenated tuple: (1, 2, 3, 4, 5, 6)
Repeated tuple: (1, 2, 3, 1, 2, 3, 1, 2, 3)
Is 20 in the tuple? True
Is 100 in the tuple? False


### Immutability Demo

In [3]:
# Trying to modify a tuple (will raise an error)
my_tuple = (10, 20, 30)
try:
    my_tuple[0] = 100
except TypeError as e:
    print('Error:', e)

Error: 'tuple' object does not support item assignment


## 3. List <a id='list'></a>

### Definition and Basic Features
- **Definition**: A list is a mutable, ordered collection of elements.
- **Mutability**: Elements can be added, removed, or modified after creation.
- **Heterogeneous**: Can contain elements of different data types.
- **Ordered**: Elements maintain their insertion order.

In [4]:
# List creation examples
# Method 1: Using square brackets
list1 = [1, 2, 3, 4, 5]
print('List 1:', list1)

# Method 2: Using list() constructor
list2 = list([1, 2, 3, 4, 5])
print('List 2:', list2)

# Empty list
empty_list = []
print('Empty list:', empty_list)

# List with mixed data types
mixed_list = [1, 'hello', 3.14, True]
print('Mixed list:', mixed_list)

List 1: [1, 2, 3, 4, 5]
List 2: [1, 2, 3, 4, 5]
Empty list: []
Mixed list: [1, 'hello', 3.14, True]


### Common Operations

In [9]:
# Accessing elements (indexing)
my_list = [10, 20, 30, 40, 50]
print('First element:', my_list[0])
print('Last element:', my_list[-1])

# Slicing
print('Slice from index 1 to 3:', my_list[1:4])
print('Every other element:', my_list[::2])

# Length
print('Length of list:', len(my_list))

# Modifying elements
my_list[0] = 100
print('Modified list:', my_list)

# Adding elements
# Append (adds to end)
my_list.append(60)
print('After append:', my_list)

# Insert (adds at specific position)
my_list.insert(1, 15)
print('After insert:', my_list)



First element: 10
Last element: 50
Slice from index 1 to 3: [20, 30, 40]
Every other element: [10, 30, 50]
Length of list: 5
Modified list: [100, 20, 30, 40, 50]
After append: [100, 20, 30, 40, 50, 60]
After insert: [100, 15, 20, 30, 40, 50, 60]


In [12]:
my_list = [10, 20, 30, 40, 50]
# Extend (adds multiple elements)
my_list.extend([70, 80])
print('After extend:', my_list)

# Removing elements
# Remove by value
my_list.remove(30)
print('After remove:', my_list)


# Pop by index (removes and returns element at specified index)
popped_by_index = my_list.pop(1)  # 移除索引为1的元素
print('Popped by index:', popped_by_index)
print('After pop(1):', my_list)


# Pop by index (default: last element)
popped = my_list.pop()
print('Popped element:', popped)
print('After pop:', my_list)

# Concatenation
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print('Concatenated list:', list_a + list_b)

# Repetition
print('Repeated list:', list_a * 3)

# Membership check
print('Is 20 in the list?', 20 in my_list)
print('Is 70 in the list?', 70 in my_list)

After extend: [10, 20, 30, 40, 50, 70, 80]
After remove: [10, 20, 40, 50, 70, 80]
Popped by index: 20
After pop(1): [10, 40, 50, 70, 80]
Popped element: 80
After pop: [10, 40, 50, 70]
Concatenated list: [1, 2, 3, 4, 5, 6]
Repeated list: [1, 2, 3, 1, 2, 3, 1, 2, 3]
Is 20 in the list? False
Is 70 in the list? True


## 4. NumPy ndarray <a id='numpy-ndarray'></a>

### Definition and Basic Features
- **Definition**: A NumPy ndarray (n-dimensional array) is a homogeneous, multidimensional array.
- **Homogeneous**: All elements must be of the same data type.
- **Efficient**: Optimized for numerical operations and memory usage.
- **Multidimensional**: Can have any number of dimensions.

In [15]:
import numpy as np

# ndarray creation examples
# Method 1: Using np.array()
arr1 = np.array([1, 2, 3, 4, 5])
print('1D array:', arr1)
print('Shape:', arr1.shape)
print('Data type:', arr1.dtype)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2D array:')
print(arr2)
print('Shape:', arr2.shape)

# Method 2: Using zeros()
zeros_arr = np.zeros((2, 3))
print('Zeros array:')
print(zeros_arr)

# Method 3: Using ones()
ones_arr = np.ones((3, 2))
print('Ones array:')
print(ones_arr)

# Method 4: Using arange()
range_arr = np.arange(0, 10, 2)
print('Range array:', range_arr)

# Method 5: Using linspace()
linspace_arr = np.linspace(0, 1, 5)
print('Linspace array:', linspace_arr)

1D array: [1 2 3 4 5]
Shape: (5,)
Data type: int64
2D array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


### Common Operations

In [18]:
import numpy as np

# Accessing elements (indexing)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Array:')
print(arr)
print('Element at (0, 0):', arr[0, 0])
print('Element at (1, 2):', arr[1, 2])

# Slicing
print('First row:', arr[0, :])
print('First column:', arr[:, 0])
print('Subarray (rows 0-1, columns 1-2):')
print(arr[0:2, 1:3])

# Shape and size
print('Shape:', arr.shape)
print('Number of elements:', arr.size)
print('Number of dimensions:', arr.ndim)

# Modifying elements
arr[0, 0] = 100
print('Modified array:')
print(arr)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 0): 1
Element at (1, 2): 6
First row: [1 2 3]
First column: [1 4 7]
Subarray (rows 0-1, columns 1-2):
[[2 3]
 [5 6]]
Shape: (3, 3)
Number of elements: 9
Number of dimensions: 2
Modified array:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [19]:

# Mathematical operations (element-wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('arr1:', arr1)
print('arr2:', arr2)
print('arr1 + arr2:', arr1 + arr2)
print('arr1 * arr2:', arr1 * arr2)
print('arr1 * 2:', arr1 * 2)

# Aggregation functions
print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Max:', np.max(arr))
print('Min:', np.min(arr))

arr1: [1 2 3]
arr2: [4 5 6]
arr1 + arr2: [5 7 9]
arr1 * arr2: [ 4 10 18]
arr1 * 2: [2 4 6]
Sum: 144
Mean: 16.0
Max: 100
Min: 2


## 5. Pandas DataFrame <a id='pandas-dataframe'></a>

### Definition and Basic Features
- **Definition**: A Pandas DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.
- **Labeled axes**: Has both row and column labels.
- **Heterogeneous**: Columns can have different data types.
- **Versatile**: Supports many operations for data manipulation and analysis.

In [ ]:
import pandas as pd
import numpy as np

# DataFrame creation examples 
# Method 1: From a dictionary 
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}
df1 = pd.DataFrame(data)
print('DataFrame from dictionary:')
print(df1)

# Method 2: From a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df2 = pd.DataFrame(arr, columns=['A', 'B', 'C'], index=['X', 'Y', 'Z'])
print('DataFrame from NumPy array:')
print(df2)

# Method 3: From a list of dictionaries
data_list = [
    {'Name': 'David', 'Age': 40, 'City': 'Tokyo'},
    {'Name': 'Eve', 'Age': 45, 'City': 'Sydney'}
]
df3 = pd.DataFrame(data_list) 
print('DataFrame from list of dictionaries:')
print(df3) 

DataFrame from dictionary:
      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
DataFrame from NumPy array:
   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9
DataFrame from list of dictionaries:
    Name  Age    City
0  David   40   Tokyo
1    Eve   45  Sydney


### Common Operations

In [4]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data)
print('\n Original DataFrame:')
print(df) 

# Accessing columns
print('\n Name column:')
print(df['Name'])

print('\n Age and Salary columns:') 
print(df[['Age', 'Salary']]) 



 Original DataFrame:
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Paris   70000
3    David   40     Tokyo   80000
4      Eve   45    Sydney   90000

 Name column:
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str

 Age and Salary columns:
   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000
4   45   90000


In [21]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}
df = pd.DataFrame(data)
print('\n Original DataFrame:')
print(df) 

# Accessing rows
# By index (iloc)
# print('\n First row (iloc):')
# print(df.iloc[0]) 

print('\n First row (iloc):')
print(df.iloc[0:1]) 

print('\n Rows 1-2 (iloc):')
print(df.iloc[1:3]) 

# By label (loc)
# Set the 'Name' column as the new index column
df_indexed = df.set_index('Name')
# remove the name of the new index column
df_indexed.index.name = None  

print('\n \n DataFrame with custom index:')
print(df_indexed) 
 
# print('\n \n Row for Bob (loc):')
# print(df_indexed.loc['Bob'])

# Return a DataFrame instead of a Series by using a double square brackets.
print('\n \n Row for Bob (loc):')
print(df_indexed.loc[['Bob']])



 Original DataFrame:
      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Paris   70000
3    David   40     Tokyo   80000
4      Eve   45    Sydney   90000

 First row (iloc):
    Name  Age      City  Salary
0  Alice   25  New York   50000

 Rows 1-2 (iloc):
      Name  Age    City  Salary
1      Bob   30  London   60000
2  Charlie   35   Paris   70000

 
 DataFrame with custom index:
         Age      City  Salary
Alice     25  New York   50000
Bob       30    London   60000
Charlie   35     Paris   70000
David     40     Tokyo   80000
Eve       45    Sydney   90000

 
 Row for Bob (loc):
     Age    City  Salary
Bob   30  London   60000


In [ ]:

# Modifying data
df['Salary'] = df['Salary'] * 1.1  # Increase salary by 10%
print('DataFrame after salary increase:')
print(df)

# Adding a new column
df['Bonus'] = df['Salary'] * 0.1
print('\n DataFrame with Bonus column:')
print(df)

# Removing a column
df = df.drop('Bonus', axis=1)
print('\n DataFrame after removing Bonus column:')
print(df)

# Filtering rows
print('\n Employees older than 35:') 
print(df[df['Age'] > 35]) 

# Basic statistics 
print('\n Basic statistics:') 
print(df.describe()) 

DataFrame after salary increase:
      Name  Age      City       Salary       Bonus
0    Alice   25  New York  107179.4405   9743.5855
1      Bob   30    London  128615.3286  11692.3026
2  Charlie   35     Paris  150051.2167  13641.0197
3    David   40     Tokyo  171487.1048  15589.7368
4      Eve   45    Sydney  192922.9929  17538.4539

 DataFrame with Bonus column:
      Name  Age      City       Salary        Bonus
0    Alice   25  New York  107179.4405  10717.94405
1      Bob   30    London  128615.3286  12861.53286
2  Charlie   35     Paris  150051.2167  15005.12167
3    David   40     Tokyo  171487.1048  17148.71048
4      Eve   45    Sydney  192922.9929  19292.29929

 DataFrame after removing Bonus column:
      Name  Age      City       Salary
0    Alice   25  New York  107179.4405
1      Bob   30    London  128615.3286
2  Charlie   35     Paris  150051.2167
3    David   40     Tokyo  171487.1048
4      Eve   45    Sydney  192922.9929

 Employees older than 35:
    Name  Age   

## 6. Comparison Summary <a id='comparison-summary'></a>

| Feature | Tuple | List | NumPy ndarray | Pandas DataFrame |
|---------|-------|------|---------------|------------------|
| Mutability | Immutable | Mutable | Mutable | Mutable |
| Homogeneity | Heterogeneous | Heterogeneous | Homogeneous | Heterogeneous (columns) |
| Dimensions | 1D | 1D (can contain lists) | N-dimensional | 2D (primary) |
| Labeling | No labels | No labels | No labels | Row and column labels |
| Memory Efficiency | High | Moderate | Very High | Moderate |
| Numerical Operations | Limited | Limited | Excellent | Good (via NumPy) |
| Data Analysis Capabilities | None | None | Basic | Advanced |
| Creation Syntax | `(1, 2, 3)` | `[1, 2, 3]` | `np.array([1, 2, 3])` | `pd.DataFrame({'col': [1, 2, 3]})` |

## 7. Conclusion <a id='conclusion'></a>

### When to Use Each Data Structure

- **Tuple**: When you need an immutable collection of elements, such as function return values or fixed data.
- **List**: When you need a mutable, general-purpose collection that can hold mixed data types.
- **NumPy ndarray**: When you need efficient numerical operations on large datasets, especially for scientific computing.
- **Pandas DataFrame**: When you need to work with tabular data, perform data analysis, or handle labeled data with different types.

Each data structure has its own strengths and use cases. Choosing the right one depends on the specific requirements of your task, such as mutability needs, data types, performance considerations, and analysis requirements.